"""
Legal document template engine.
Structured templates for Bail Application, Legal Notice, Affidavit, Petition, Agreement.
"""

from typing import Any

# Document types supported by the system
DOCUMENT_TYPES = [
    "bail_application",
    "legal_notice",
    "affidavit",
    "petition",
    "agreement",
]

# Templates use {placeholder} style; fill with case details and leave {generated_facts} for LLM.
TEMPLATES = {
    "bail_application": """
IN THE COURT OF {court_name}

BAIL APPLICATION
UNDER SECTION {section}

Applicant: {client_name}

Most Respectfully Submitted:

{generated_facts}

PRAYER

It is therefore prayed that this Hon'ble Court may kindly grant bail to the applicant on such terms and conditions as this Hon'ble Court may deem fit.

Place:
Date:

Applicant
{client_name}
""",
    "legal_notice": """
LEGAL NOTICE
UNDER SECTION 80 CODE OF CIVIL PROCEDURE, 1908

From:
{client_name}
Address: {client_address}

To:
{opponent_name}
Address: {opponent_address}

Subject: {subject}

Sir/Madam,

{generated_facts}

You are hereby called upon to comply with the above within 30 (thirty) days from the receipt of this notice, failing which my client shall be constrained to initiate appropriate legal proceedings against you at your risk as to cost and consequences.

Place:
Date:

Advocate for {client_name}
""",
    "affidavit": """
IN THE COURT OF {court_name}

AFFIDAVIT

I, {client_name}, son/daughter of {father_name}, aged about {age} years, resident of {client_address}, do hereby solemnly affirm and state as under:

{generated_facts}

That the contents of the above affidavit are true and correct to the best of my knowledge and belief and nothing material has been concealed therefrom.

Deponent
{client_name}

Place:
Date:

Verification:
Verified at ________ on this ________ day of ________ that the contents of the above affidavit are true and correct.
""",
    "petition": """
IN THE COURT OF {court_name}

{petition_type}
(Civil/Criminal Petition No. ________ of ________)

Petitioner: {client_name}

Versus

Respondent: {opponent_name}

PETITION UNDER {section}

Most Respectfully Submitted:

{generated_facts}

PRAYER

In view of the above, it is most respectfully prayed that this Hon'ble Court may be pleased to:

(a) _____________________________________________
(b) _____________________________________________

Place:
Date:

Petitioner / Advocate for Petitioner
{client_name}
""",
    "agreement": """
AGREEMENT

This Agreement is made on the ________ day of ________ at ________

BETWEEN:

1. {client_name} (Party of the First Part)
   Address: {client_address}

2. {opponent_name} (Party of the Second Part)
   Address: {opponent_address}

WHEREAS:

{generated_facts}

NOW THEREFORE IT IS HEREBY AGREED AS FOLLOWS:

1. _____________________________________________
2. _____________________________________________
3. _____________________________________________

IN WITNESS WHEREOF the parties hereto have set their hands on the date first above written.

Party of the First Part          Party of the Second Part
{client_name}                    {opponent_name}
""",
}

# Default placeholder values when not provided
DEFAULT_PLACEHOLDERS = {
    "court_name": "District Court",
    "section": "Applicable Section",
    "client_name": "Applicant/Client",
    "client_address": "Address to be inserted",
    "opponent_name": "Opposite Party",
    "opponent_address": "Address to be inserted",
    "subject": "Subject of Notice",
    "father_name": "Father's Name",
    "age": "Age",
    "petition_type": "Petition",
    "generated_facts": "[FACTS AND SUBSTANCE TO BE GENERATED BY THE MODEL]",
}


def get_template(document_type: str) -> str:
    """Return template for document_type; raises KeyError if unknown."""
    if document_type not in TEMPLATES:
        raise KeyError(f"Unknown document_type: {document_type}. Supported: {list(TEMPLATES.keys())}")
    return TEMPLATES[document_type]


def fill_template(document_type: str, placeholders: dict[str, Any]) -> str:
    """
    Fill template with placeholders. Missing keys are replaced with defaults.
    Keeps {generated_facts} as placeholder for LLM output.
    """
    template = get_template(document_type)
    merged = {**DEFAULT_PLACEHOLDERS, **placeholders}
    # Ensure generated_facts is present for LLM
    if "generated_facts" not in merged or merged["generated_facts"] is None:
        merged["generated_facts"] = "[FACTS AND SUBSTANCE TO BE GENERATED BY THE MODEL]"
    result = template
    for key, value in merged.items():
        if value is None:
            value = DEFAULT_PLACEHOLDERS.get(key, "")
        result = result.replace("{" + key + "}", str(value).strip())
    return result


def get_placeholder_keys(document_type: str) -> list[str]:
    """Return list of placeholder keys used in the template."""
    import re
    template = get_template(document_type)
    return list(set(re.findall(r"\{(\w+)\}", template)))
